In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
data = pd.read_csv("/Volumes/GoogleDrive/共享云端硬盘/Predictive Analytics Project/train.csv")

In [2]:
%matplotlib inline
# import necessary libraries and specify that graphs should be plotted inline. 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import tree, neighbors, datasets, metrics, svm
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_curve, auc, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import scikitplot as skplt

In [3]:
data=data.drop(['Unnamed: 0','Unnamed: 0.1','SK_ID_CURR','set_x','set_y'], axis=1)

In [4]:
datacount=data.count()

In [5]:
data=data.drop(list(datacount[datacount<300000].index),axis=1)

In [6]:
data=data.fillna(data.mean())

In [7]:
data=data[(data['TARGET']==0) | (data['TARGET']==1)]

In [8]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(data)
df = pd.DataFrame(x_scaled)

In [9]:
normalized_df=(data-data.mean())/data.std()

In [10]:
df.columns=[list(data.columns)]

In [11]:
train_x = df.drop(['TARGET'], axis=1)
train_y = data['TARGET']    #target column i.e price range

/Users/fbzhan/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:3812: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  new_axis = axis.drop(labels, errors=errors)


In [12]:
Best = SelectKBest(score_func=chi2,k=2).fit(train_x, train_y)

In [13]:
bestscores = pd.DataFrame(Best.scores_,index=train_x.columns)

In [14]:
bestscores=bestscores.sort_values(by=0,ascending=False)

In [15]:
bestscores600=bestscores[bestscores.values>1]

In [16]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(train_x, train_y)

/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [17]:
importancescores = pd.DataFrame(model.feature_importances_,index=train_x.columns)

In [18]:
importancescores=importancescores.sort_values(by=0,ascending=False)
importancescores463=importancescores[importancescores.values>.001]
importancescores463.index

MultiIndex(levels=[['AMT_ANNUITY', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'AMT_INCOME_TOTAL', 'CNT_CHILDREN', 'CNT_FAM_MEMBERS', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION', 'DEF_30_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'EXT_SOURCE_2', 'FLAG_CONT_MOBILE', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_EMAIL', 'FLAG_EMP_PHONE', 'FLAG_MOBIL', 'FLAG_PHONE', 'FLAG_WORK_PHONE', 'HOUR_APPR_PROCESS_START', 'LIVE_CITY_NOT_WORK_CITY', 'LIVE_REGION_NOT_WORK_REGION', 'OBS_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'REGION_POPULATION_RELATIVE', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_

In [19]:
bestandimportantfeatures=bestscores600.index & importancescores463.index

In [20]:
print(len(bestandimportantfeatures), 'features')
bestandimportantfeatures

110 features


MultiIndex(levels=[['AMT_ANNUITY', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'CNT_CHILDREN', 'CNT_FAM_MEMBERS', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION', 'DEF_30_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'EXT_SOURCE_2', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_8', 'FLAG_PHONE', 'FLAG_WORK_PHONE', 'HOUR_APPR_PROCESS_START', 'LIVE_CITY_NOT_WORK_CITY', 'LIVE_REGION_NOT_WORK_REGION', 'REGION_POPULATION_RELATIVE', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'app_CODE_GENDER_F_count', 'app_CODE_GENDER_M_count', 'app_EMERGENCYSTATE_MODE_No_count', 'app_EMERGENCYSTATE_MODE_Yes_count', 'app_FLAG_OWN_CAR_N_count', 'app_FLAG_OWN_CAR_Y_count', 'app_FLAG_OWN_REALTY_N_count', 'app_FLAG_OWN_REALTY_Y_count', 'app_FONDKAPREMONT_MODE_not specified_count', 'app_FONDKAPREMONT_MODE_o

In [21]:
names=[]
for x in bestandimportantfeatures.values:
    names.append(x[0])

In [22]:
x_train = df[names].values

In [23]:
y_train = data['TARGET'].values
#y_train = pd.DataFrame(y_train)

# testing data
data1 = pd.read_csv("../input/dataset/test.csv")
data1=data1.fillna(data1.mean())

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled1 = min_max_scaler.fit_transform(data1)
df1 = pd.DataFrame(x_scaled1)

#normalized_df1=(data1-data1.mean())/data1.std()

#df1.columns=[list(data1.columns)]
#x_test = df1[names].values

In [24]:
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression 

In [ ]:
# Create logistic regression
logistic = LogisticRegression()

In [ ]:
# Create regularization penalty space
penalty = ['l1', 'l2']

# Create regularization hyperparameter distribution using uniform distribution
C = uniform(loc=0, scale=4)

# Create hyperparameter options
hyperparameters = dict(C=C, penalty=penalty)

In [ ]:
# Create randomized search 5-fold cross validation and 100 iterations
clf = RandomizedSearchCV(logistic, hyperparameters, random_state=1, n_iter=20, cv=5, verbose=0, n_jobs=-1)

In [ ]:
# Fit randomized search
best_model = clf.fit(x_train, y_train)

In [ ]:
# View best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])

In [25]:
lr = linear_model.LogisticRegression(C=0.0001, penalty = 'L2')
lr.fit(x_train, y_train)

/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=0.0001, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
def evaluate_model(ytest, ypred, ypred_proba = None):
    if ypred_proba is not None:
        print('ROC-AUC score of the model:   {}'.format(roc_auc_score(ytest, ypred_proba[:, 1])))
    print('Accuracy of the model: {}\n'.format(accuracy_score(ytest, ypred)))
    print('Classification report: \n{}\n'.format(classification_report(ytest, ypred)))
    print('Confusion matrix: \n{}\n'.format(confusion_matrix(ytest, ypred)))

In [29]:
folds = list(StratifiedKFold(10, shuffle=True).split(x_train, y_train))
for i, (train_idx, valid_idx) in enumerate(folds):
    
    ytrain = np.array(y_train)
    X_train = x_train[train_idx]
    Y_train = ytrain[train_idx]
    X_valid = x_train[valid_idx]
    Y_valid = ytrain[valid_idx]
    
    lr.fit(X_train, Y_train)
    pred = lr.predict(X_valid)
    pred_proba = lr.predict_proba(X_valid)
    
    print('\ncv: {}\n'.format(i))
    evaluate_model(Y_valid, pred, pred_proba)

/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 0

ROC-AUC score of the model:   0.6275891243162479
Accuracy of the model: 0.9192572840790842

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28269
         1.0       0.00      0.00      0.00      2483

    accuracy                           0.92     30752
   macro avg       0.46      0.50      0.48     30752
weighted avg       0.85      0.92      0.88     30752


Confusion matrix: 
[[28269     0]
 [ 2483     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 1

ROC-AUC score of the model:   0.634638581727497
Accuracy of the model: 0.9192572840790842

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28269
         1.0       0.00      0.00      0.00      2483

    accuracy                           0.92     30752
   macro avg       0.46      0.50      0.48     30752
weighted avg       0.85      0.92      0.88     30752


Confusion matrix: 
[[28269     0]
 [ 2483     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 2

ROC-AUC score of the model:   0.6290197161847402
Accuracy of the model: 0.9192572840790842

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28269
         1.0       0.00      0.00      0.00      2483

    accuracy                           0.92     30752
   macro avg       0.46      0.50      0.48     30752
weighted avg       0.85      0.92      0.88     30752


Confusion matrix: 
[[28269     0]
 [ 2483     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 3

ROC-AUC score of the model:   0.6250750317768025
Accuracy of the model: 0.9192572840790842

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28269
         1.0       0.00      0.00      0.00      2483

    accuracy                           0.92     30752
   macro avg       0.46      0.50      0.48     30752
weighted avg       0.85      0.92      0.88     30752


Confusion matrix: 
[[28269     0]
 [ 2483     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 4

ROC-AUC score of the model:   0.6243422979397616
Accuracy of the model: 0.9192572840790842

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28269
         1.0       0.00      0.00      0.00      2483

    accuracy                           0.92     30752
   macro avg       0.46      0.50      0.48     30752
weighted avg       0.85      0.92      0.88     30752


Confusion matrix: 
[[28269     0]
 [ 2483     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 5

ROC-AUC score of the model:   0.6170715614627733
Accuracy of the model: 0.9192871776527592

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28269
         1.0       0.00      0.00      0.00      2482

    accuracy                           0.92     30751
   macro avg       0.46      0.50      0.48     30751
weighted avg       0.85      0.92      0.88     30751


Confusion matrix: 
[[28269     0]
 [ 2482     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 6

ROC-AUC score of the model:   0.6304582608478513
Accuracy of the model: 0.9192845528455285

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28268
         1.0       0.00      0.00      0.00      2482

    accuracy                           0.92     30750
   macro avg       0.46      0.50      0.48     30750
weighted avg       0.85      0.92      0.88     30750


Confusion matrix: 
[[28268     0]
 [ 2482     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 7

ROC-AUC score of the model:   0.6366859785816589
Accuracy of the model: 0.9192845528455285

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28268
         1.0       0.00      0.00      0.00      2482

    accuracy                           0.92     30750
   macro avg       0.46      0.50      0.48     30750
weighted avg       0.85      0.92      0.88     30750


Confusion matrix: 
[[28268     0]
 [ 2482     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 8

ROC-AUC score of the model:   0.6333069303171316
Accuracy of the model: 0.9192845528455285

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28268
         1.0       0.00      0.00      0.00      2482

    accuracy                           0.92     30750
   macro avg       0.46      0.50      0.48     30750
weighted avg       0.85      0.92      0.88     30750


Confusion matrix: 
[[28268     0]
 [ 2482     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



cv: 9

ROC-AUC score of the model:   0.6256988480352724
Accuracy of the model: 0.9192845528455285

Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     28268
         1.0       0.00      0.00      0.00      2482

    accuracy                           0.92     30750
   macro avg       0.46      0.50      0.48     30750
weighted avg       0.85      0.92      0.88     30750


Confusion matrix: 
[[28268     0]
 [ 2482     0]]



/Users/fbzhan/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
